# promtail-config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot-app
          __path__: /var/lib/docker/containers/*/*.log

  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: applogs
          __path__: /logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: @timestamp
            level: level
            threadName: thread_name
            loggerName: logger_name
            message: message
            context: context
      - labels:
          level: ''
      - timestamp:
          source: timestamp
          format: RFC3339Nano