spring:
  application:
    name: WorkoutMate

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  # redis ?? ?? ? ?? ?? ? ??
#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}

  mvc:
    servlet:
      path: /api

# 시간 직렬화 위해
  jackson:
    serialization:
      write-date-keys-as-timestamps: false


server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}

logging:
  level:
    org.springframework.jdbc.core: DEBUG