spring:
  profiles:
    # 환경변수로 받되, 기본은 dev
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: WorkoutMate

  # env 파일 사용 위해
  config:
    import: optional:file:.env[.properties]

  mvc:
    servlet:
      path: /api

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        format_sql: false

  cache:
    type: redis

# 시간 직렬화 위해
  jackson:
    serialization:
      write-date-keys-as-timestamps: false

  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from: ${SENDGRID_FROM_EMAIL}
    template-id: ${SENDGRID_TEMPLATE_ID}

server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}

logging:
  level:
    org.springframework.jdbc.core: DEBUG

# Spring actuator 관련 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"

