spring:
  profiles:
    # 환경변수로 받되, 기본은 dev
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: WorkoutMate

  # env 파일 사용 위해
  config:
    import: optional:file:.env[.properties]

  mvc:
    servlet:
      path: /api

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false

  # 시간 직렬화 위해
  jackson:
    serialization:
      write-date-keys-as-timestamps: false

  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from: ${SENDGRID_FROM_EMAIL}
    template-id: ${SENDGRID_TEMPLATE_ID}

server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}

logging:
  level:
    org.springframework.jdbc.core: DEBUG

  # 가중치 계산
recommendation:
  weights:
    participation: 0.4
    zzim: 0.2
    friend: 0.1
    type: 0.15
    time: 0.15
  max-candidate-size : 1000
  min-score: 0.1