spring:
  profiles:
    # 환경변수로 받되, 기본은 dev
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: WorkoutMate

  # env 파일 사용 위해
  config:
    import: optional:file:.env[.properties]

  mvc:
    servlet:
      path: /api

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        format_sql: false

  cache:
    type: redis

# 시간 직렬화 위해
  jackson:
    serialization:
      write-date-keys-as-timestamps: false

  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from: ${SENDGRID_FROM_EMAIL}
    template-id: ${SENDGRID_TEMPLATE_ID}

server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}

logging:
  level:
    org.springframework.jdbc.core: DEBUG

# Spring actuator 관련 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"

  # 가중치 계산
recommendation:
  vector:
    dim: 32
    decay_per_day: 0.95
    user_global_mix: 0.1
  friend:
    explore_days: 14
    presence_cap: 3
    presence_bonus_per_friend: 3.3
    presence_bonus_cap: 10
    inject_slots: [2, 6]
    inject_min_sim: 0.30
  time:
    rerank_enabled: true
    max_multiplier: 1.15
    center_hours: 24
    slope: 6
  rules:
    exclude_full: true
    near_full_threshold: 0.9
    near_full_penalty_percent: 2
  diversify:
    per_type_max: 4
    min_distinct_types: 2