spring:
  datasource:
    url: ${DEPLOY_DB_URL}
    username: ${DEPLOY_DB_USERNAME}
    password: ${DEPLOY_DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

  data:
    redis:
      host: ${DEPLOY_REDIS_HOST}
      port: ${DEPLOY_REDIS_PORT}
      timeout: 3000
