# db 용 docker-compose.yml

version: '3.8'

services:
  redis:
    # 사용할 이미지
    image: redis:latest
    # 컨테이너명
    container_name: redis-container
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    ports:
      - "15483:15483"
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - /home/ubuntu/db/redis/data:/data
      - /home/ubuntu/db/redis/conf/redis.conf:/usr/local/conf/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료시 재시작 여부 설정
    restart: always
    command: redis-server /usr/local/conf/redis.conf

networks:
  default:
    external: true
    name: my-network